### ISSUE TITLE
[Feature]: Make DotA 2 RPC on Main Menu is also displayed or when the Search Game is in progress

### ISSUE THREAD

**Issue by 26DiDi12** [andsfonseca/dota2-rpc-client#30]
### Are you on the latest version?

- [X] I\'m on the latest version

### Is there a fix in progress related to your proposal?

- [X] I have searched the existing issues

### Describe the solution you'd like

Сделать так, чтобы и в главном меню тоже отображалось, или когда поиск игры идёт

**Comment by andsfonseca** [comment]
Hi @26DiDi12, can u write in english? 😅

**Comment by 26DiDi12** [comment]
Hi @andsfonseca, for u: "Make DotA 2 RPC on Main Menu is also displayed or when the Search Game is in progress", sry for my Eng is very bad. 😅

**Comment by andsfonseca** [comment]
No problem, mine too xD

**Comment by andsfonseca** [comment]
412 / 5.000
Resultados de tradução
About the main menu, unfortunately the feature I'm using from Dota2-gsi doesn't tell me if the player is on the menu or is looking for matches.

I tried to detect if the program was open, but fetching open programs in memory is a danger. So I ended up just using gsi because it's safe.

In the future, if I find another alternative that allows this functionality, I'll implement it.

**Comment by andsfonseca** [comment]
About the main menu, unfortunately the feature I'm using from Dota2-gsi doesn't tell me if the player is on the menu or is looking for matches.

I tried to detect if the program was open, but fetching open programs in memory is a danger. So I ended up just using gsi because it's safe.

In the future, if I find another alternative that allows this functionality, I will implement it.

**Comment by 26DiDi12** [comment]
I'm too using a translator :)

ok, thx for answer, good luck!
